### ISSUE TITLE
Surpress plots

### ISSUE THREAD

**Issue by mps9506** [SwampThingPaul/NADA2#11]
Hi Paul,

Do you have any opinions about adding an argument that suppresses plotting in functions such as `ATS()` or `centrend()`? I know I can use `NADA::cenken()` but these functions are pretty handy one liners for me.

Thanks

**Comment by SwampThingPaul** [comment]
Hi Michael, apologies for the delay in responding. I added an argument to both `ATS()` and `centrend()` to make plotting optional. Thanks for the suggestion. Let me know if you run into any issues.
