### ISSUE TITLE
call of enparCensored incorrect

### ISSUE THREAD

**Issue by alexkowa** [SwampThingPaul/NADA2#13]
In cfit.R you call EnvStats::enparCensored with a numeric argument in ci.sample.size. This is not correct and is enforced in the next CRAN version of EnvStats. I created a pull request to fix it #12 . Please merge and update on CRAN asap so I can proceed with the EnvStats update.

**Comment by SwampThingPaul** [comment]
Hi @alexkowa, Thanks for the revision. I merged the branch in your pull request. Apologies its taken so long to respond.

**Comment by alexkowa** [comment]
Great. Will you be able to make an update on CRAN soon?

**Comment by SwampThingPaul** [comment]
Hi @alexkowa, just submitted to CRAN. Fingers crossed it will be accepted and updated soon. Thanks again and apologies for the delay.

**Comment by alexkowa** [comment]
Hi @SwampThingPaul , I see that the new version is not yet on CRAN. Probably due to the CRAN submission summer break? Will you proceed with the submission after the CRAN break?
