### ISSUE TITLE
cenpermanova example returns warnings and NA's for group means.

### ISSUE THREAD

**Issue by YoJimboDurant** [SwampThingPaul/NADA2#3]
Appears that the  `cenpermanova` has  a small issue with calculating means from the ros object it creates internally:

```
data(PbHeron)
cenpermanova(PbHeron$Liver,PbHeron$LiverCen,PbHeron$DosageGroup)

 Permutation test of mean CensData: PbHeron$Liver   by Factor: PbHeron$DosageGroup 
     9999 Permutations 
Test Statistic = 1122 to 1122       p = 0.0021 to 0.0024 
 
mean(High)    mean(Low)   
        NA           NA   
Warning messages:
1: In mean.default(ros.out) :
  argument is not numeric or logical: returning NA
2: In mean.default(ros.out) :
  argument is not numeric or logical: returning NA
```

After debugging, I noticed on line 44 of function you call mean but R is going to default mean method. I suggest changing to:

```
NADA:::mean(ros.out)
```

Thanks for making this package available!

**Comment by SwampThingPaul** [comment]
Thanks for identifying this issue. This error should be resolved in the development (i.e. GitHub) version.
